// Public & Authenticated pages (unified - navbar switches based on auth state)
export { default as Home } from './Home'
export { default as About } from './About'
export { default as Courses } from './Courses'
export { default as Login } from './Login'
export { default as Signup } from './Signup'
export { default as PrivacyPolicy } from './PrivacyPolicy'
export { default as Profile } from './Profile'
export { default as EditProfile } from './EditProfile'
export { default as MyCourses } from './MyCourses'
export { default as Wishlist } from './Wishlist'
export { default as CourseQuiz } from './CourseQuiz'
export { default as CourseAssignments } from './CourseAssignments'
export { default as CourseCertificate } from './CourseCertificate'
